### ISSUE TITLE
java.lang.NoSuchMethodError: okhttp3.Interceptor$Chain.connectTimeoutMillis()

### ISSUE THREAD

**Issue by leoshao** [oliviergauthier/gradle-appcenter-plugin#56]
```
Caused by: java.lang.NoSuchMethodError: okhttp3.Interceptor$Chain.connectTimeoutMillis()I
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:107)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.betomorrow.gradle.appcenter.infra.AppCenterAPIFactory$create$builder$1.invoke(AppCenterAPIFactory.kt:21)
	at com.betomorrow.gradle.appcenter.infra.AppCenterAPIFactory$create$builder$1.invoke(AppCenterAPIFactory.kt:7)
	at com.betomorrow.gradle.appcenter.infra.LambdaInterceptor.intercept(OkHttpBuilder.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
	at okhttp3.RealCall.execute(RealCall.java:92)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
	at com.betomorrow.gradle.appcenter.infra.AppCenterUploader.uploadApk(AppCenterUploader.kt:21)
	at com.betomorrow.gradle.appcenter.tasks.UploadAppCenterTask.upload(UploadAppCenterTask.kt:35)
```

**Comment by leoshao** [comment]
seems like if "https://plugins.gradle.org/m2/" and MavenCentral() both exist, will cause this problem. Once MavenCentral removed, error goes away.

**Comment by Nilzor** [comment]
Getting the same here and I don't have `mavenCentral`

```
buildscript {
    
    repositories {
        jcenter()
        google()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$versions.gradle"
        classpath "com.appdynamics:appdynamics-gradle-plugin:$versions.appdynamics"
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:perf-plugin:1.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$versions.kotlin"
        classpath "gradle.plugin.com.betomorrow.gradle:appcenter-plugin:1.2.1"
    }
}
```

Any tips?
